{% set name = "caustics" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caustics-{{ version }}.tar.gz
  sha256: bb2d2b046ec4c28d272eb8f6448407e3d19174c13e7a956aa4c6e84d97aa1f8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-requirements-txt
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - pytorch >=2.0.0
    - astropy <6.0.0,>=5.2.1
    - caskade >=0.5.0
    - python-graphviz ==0.20.1
    - h5py >=3.8.0
    - mpmath >=1.3.0,<1.4.0
    - numba <0.59.0,>=0.58.1
    - numpy >=1.23.5
    - safetensors >=0.4.1
    - scipy >=1.8.0

test:
  imports:
    - caustics
  commands:
    - pip check
    - python -c "import caustics; assert caustics.__version__ != '0.0.0'; caustics.test()"
  requires:
    - pip

about:
  home: https://github.com/Ciela-Institute/caustics
  summary: 'The lensing pipeline of the future: GPU-accelerated, automatically-differentiable, highly modular. Currently under heavy development: expect interface changes and some imprecise/untested calculations.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - uwcdc
    - ConnorStoneAstro
